apiVersion: v1
kind: Service
metadata:
  name: k8sapi-invoker
  labels:
    app: k8sapi-invoker
spec:
  type: ClusterIP
  ports:
  - port: 8111
    protocol: TCP
    name: http
    targetPort: http
  selector:
    app: k8sapi-invoker